server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/course
    username: joel
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdb
    baselineOnMigrate: true

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://localhost:8087'